//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// <human-generated>
//      This code has been edited by a human, to meet C# naming conventions
//
//      Changes to this file will be lost if the code is regenerated, unless
//      there is a cool switch in Marc Gravell's generator that I was not aware of
// </human-generated>
//------------------------------------------------------------------------------

// Generated from: market.proto
namespace Market
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppsRequest")]
  public partial class AppsRequest : global::ProtoBuf.IExtensible
  {
    public AppsRequest() {}
    

    private AppType _appType = AppType.None;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AppType.None)]
    public AppType AppType
    {
      get { return _appType; }
      set { _appType = value; }
    }

    private string _query = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"query", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Query
    {
      get { return _query; }
      set { _query = value; }
    }

    private string _categoryId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"categoryId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CategoryId
    {
        get { return _categoryId; }
        set { _categoryId = value; }
    }

    private string _appId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"appId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AppId
    {
        get { return _appId; }
        set { _appId = value; }
    }

    private bool _withExtendedInfo = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"withExtendedInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool WithExtendedInfo
    {
      get { return _withExtendedInfo; }
      set { _withExtendedInfo = value; }
    }

    private AppsRequest.OrderType _orderType = AppsRequest.OrderType.None;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"orderType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AppsRequest.OrderType.None)]
    public AppsRequest.OrderType Order
    {
      get { return _orderType; }
      set { _orderType = value; }
    }

    private ulong _startIndex = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"startIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong StartIndex
    {
      get { return _startIndex; }
      set { _startIndex = value; }
    }

    private int _entriesCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"entriesCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EntriesCount
    {
      get { return _entriesCount; }
      set { _entriesCount = value; }
    }

    private AppsRequest.ViewType _viewType = AppsRequest.ViewType.All;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"viewType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AppsRequest.ViewType.All)]
    public AppsRequest.ViewType View
    {
      get { return _viewType; }
      set { _viewType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"OrderType")]
    public enum OrderType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"POPULAR", Value=1)]
      Popular = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEWEST", Value=2)]
      Newest = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FEATURED", Value=3)]
      Featured = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ViewType")]
    public enum ViewType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=0)]
      All = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE", Value=1)]
      Free = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAID", Value=2)]
      Paid = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppsResponse")]
  public partial class AppsResponse : global::ProtoBuf.IExtensible
  {
    public AppsResponse() {}
    
    private readonly global::System.Collections.Generic.List<App> _app = new global::System.Collections.Generic.List<App>();
    [global::ProtoBuf.ProtoMember(1, Name=@"app", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<App> Apps
    {
      get { return _app; }
    }
  

    private int _entriesCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"entriesCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EntriesCount
    {
      get { return _entriesCount; }
      set { _entriesCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Category")]
  public partial class Category : global::ProtoBuf.IExtensible
  {
    public Category() {}
    

    private int _appType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"appType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AppType
    {
      get { return _appType; }
      set { _appType = value; }
    }

    private string _title = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title
    {
      get { return _title; }
      set { _title = value; }
    }

    private string _categoryId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"categoryId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CategoryId
    {
      get { return _categoryId; }
      set { _categoryId = value; }
    }

    private string _subtitle = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"subtitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Subtitle
    {
      get { return _subtitle; }
      set { _subtitle = value; }
    }
    private readonly global::System.Collections.Generic.List<Category> _subCategories = new global::System.Collections.Generic.List<Category>();
    [global::ProtoBuf.ProtoMember(8, Name=@"subCategories", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Category> SubCategories
    {
      get { return _subCategories; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommentsRequest")]
  public partial class CommentsRequest : global::ProtoBuf.IExtensible
  {
    public CommentsRequest() {}
    

    private string _appId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AppId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private int _startIndex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StartIndex
    {
      get { return _startIndex; }
      set { _startIndex = value; }
    }

    private int _entriesCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"entriesCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EntriesCount
    {
      get { return _entriesCount; }
      set { _entriesCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommentsResponse")]
  public partial class CommentsResponse : global::ProtoBuf.IExtensible
  {
    public CommentsResponse() {}
    
    private readonly global::System.Collections.Generic.List<Comment> _comments = new global::System.Collections.Generic.List<Comment>();
    [global::ProtoBuf.ProtoMember(1, Name=@"comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Comment> Comments
    {
      get { return _comments; }
    }
  

    private int _entriesCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"entriesCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EntriesCount
    {
      get { return _entriesCount; }
      set { _entriesCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"App")]
  public partial class App : global::ProtoBuf.IExtensible
  {
    public App() {}
    

    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title
    {
      get { return _title; }
      set { _title = value; }
    }

    private AppType _appType = AppType.None;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"appType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AppType.None)]
    public AppType AppType
    {
      get { return _appType; }
      set { _appType = value; }
    }

    private string _creator = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Creator
    {
      get { return _creator; }
      set { _creator = value; }
    }

    private string _version = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Version
    {
      get { return _version; }
      set { _version = value; }
    }

    private string _price = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Price
    {
      get { return _price; }
      set { _price = value; }
    }

    private string _rating = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rating", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Rating
    {
      get { return _rating; }
      set { _rating = value; }
    }

    private int _ratingsCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ratingsCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RatingsCount
    {
      get { return _ratingsCount; }
      set { _ratingsCount = value; }
    }

    private App.ExtendedInfo _extendedinfo = default(App.ExtendedInfo);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"extendedinfo", DataFormat = global::ProtoBuf.DataFormat.Group)]
    //[global::System.ComponentModel.DefaultValue(default(App.ExtendedInfo))]
    public App.ExtendedInfo Extendedinfo
    {
      get { return _extendedinfo; }
      set { _extendedinfo = value; }
    }

    private string _creatorId = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"creatorId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CreatorId
    {
      get { return _creatorId; }
      set { _creatorId = value; }
    }

    private string _packageName = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"packageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PackageName
    {
      get { return _packageName; }
      set { _packageName = value; }
    }

    private int _versionCode = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"versionCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int VersionCode
    {
      get { return _versionCode; }
      set { _versionCode = value; }
    }

    private string _priceCurrency = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"priceCurrency", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PriceCurrency
    {
      get { return _priceCurrency; }
      set { _priceCurrency = value; }
    }

    private int _priceMicros = default(int);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"priceMicros", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PriceMicros
    {
      get { return _priceMicros; }
      set { _priceMicros = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExtendedInfo")]
  public partial class ExtendedInfo : global::ProtoBuf.IExtensible
  {
    public ExtendedInfo() {}
    

    private string _description = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _description; }
      set { _description = value; }
    }

    private int _downloadsCount = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"downloadsCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int DownloadsCount
    {
      get { return _downloadsCount; }
      set { _downloadsCount = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _permissionId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"permissionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> PermissionId
    {
      get { return _permissionId; }
    }
  

    private int _installSize = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"installSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int InstallSize
    {
      get { return _installSize; }
      set { _installSize = value; }
    }

    private string _packageName = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"packageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PackageName
    {
      get { return _packageName; }
      set { _packageName = value; }
    }

    private string _category = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Category
    {
      get { return _category; }
      set { _category = value; }
    }

    private string _contactEmail = "";
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"contactEmail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ContactEmail
    {
      get { return _contactEmail; }
      set { _contactEmail = value; }
    }

    private string _downloadsCountText = "";
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"downloadsCountText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DownloadsCountText
    {
      get { return _downloadsCountText; }
      set { _downloadsCountText = value; }
    }

    private string _contactPhone = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"contactPhone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ContactPhone
    {
      get { return _contactPhone; }
      set { _contactPhone = value; }
    }

    private string _contactWebsite = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"contactWebsite", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ContactWebsite
    {
      get { return _contactWebsite; }
      set { _contactWebsite = value; }
    }

    private int _screenshotsCount = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"screenshotsCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ScreenshotsCount
    {
      get { return _screenshotsCount; }
      set { _screenshotsCount = value; }
    }

    private string _promoText = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"promoText", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PromoText
    {
      get { return _promoText; }
      set { _promoText = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Comment")]
  public partial class Comment : global::ProtoBuf.IExtensible
  {
    public Comment() {}
    

    private string _text = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Text
    {
      get { return _text; }
      set { _text = value; }
    }

    private int _rating = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rating", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Rating
    {
      get { return _rating; }
      set { _rating = value; }
    }

    private string _authorName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"authorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AuthorName
    {
      get { return _authorName; }
      set { _authorName = value; }
    }

    private ulong _creationTime = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creationTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CreationTime
    {
      get { return _creationTime; }
      set { _creationTime = value; }
    }

    private string _authorId = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"authorId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AuthorId
    {
      get { return _authorId; }
      set { _authorId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CategoriesRequest")]
  public partial class CategoriesRequest : global::ProtoBuf.IExtensible
  {
    public CategoriesRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CategoriesResponse")]
  public partial class CategoriesResponse : global::ProtoBuf.IExtensible
  {
    public CategoriesResponse() {}
    
    private readonly global::System.Collections.Generic.List<Category> _categories = new global::System.Collections.Generic.List<Category>();
    [global::ProtoBuf.ProtoMember(1, Name=@"categories", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Category> Categories
    {
      get { return _categories; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubCategoriesRequest")]
  public partial class SubCategoriesRequest : global::ProtoBuf.IExtensible
  {
    public SubCategoriesRequest() {}
    

    private AppType _appType = AppType.None;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AppType.None)]
    public AppType AppType
    {
      get { return _appType; }
      set { _appType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubCategoriesResponse")]
  public partial class SubCategoriesResponse : global::ProtoBuf.IExtensible
  {
    public SubCategoriesResponse() {}
    
    private readonly global::System.Collections.Generic.List<Category> _category = new global::System.Collections.Generic.List<Category>();
    [global::ProtoBuf.ProtoMember(1, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Category> Category
    {
      get { return _category; }
    }
  

    private string _subCategoryDisplay = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subCategoryDisplay", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SubCategoryDisplay
    {
      get { return _subCategoryDisplay; }
      set { _subCategoryDisplay = value; }
    }

    private int _subCategoryId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subCategoryId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SubCategoryId
    {
      get { return _subCategoryId; }
      set { _subCategoryId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestContext")]
  public partial class RequestContext : global::ProtoBuf.IExtensible
  {
    public RequestContext() {}
    
    private string _authSubToken;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"authSubToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AuthSubToken
    {
      get { return _authSubToken; }
      set { _authSubToken = value; }
    }
    private int _unknown1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unknown1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Unknown1
    {
      get { return _unknown1; }
      set { _unknown1 = value; }
    }
    private int _version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _androidId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"androidId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AndroidId
    {
      get { return _androidId; }
      set { _androidId = value; }
    }

    private string _deviceAndSdkVersion = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deviceAndSdkVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string DeviceAndSdkVersion
    {
      get { return _deviceAndSdkVersion; }
      set { _deviceAndSdkVersion = value; }
    }

    private string _userLanguage = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userLanguage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserLanguage
    {
      get { return _userLanguage; }
      set { _userLanguage = value; }
    }

    private string _userCountry = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"userCountry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string UserCountry
    {
      get { return _userCountry; }
      set { _userCountry = value; }
    }

    private string _operatorAlpha = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"operatorAlpha", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OperatorAlpha
    {
      get { return _operatorAlpha; }
      set { _operatorAlpha = value; }
    }

    private string _simOperatorAlpha = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"simOperatorAlpha", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SimOperatorAlpha
    {
      get { return _simOperatorAlpha; }
      set { _simOperatorAlpha = value; }
    }

    private string _operatorNumeric = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"operatorNumeric", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OperatorNumeric
    {
      get { return _operatorNumeric; }
      set { _operatorNumeric = value; }
    }

    private string _simOperatorNumeric = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"simOperatorNumeric", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SimOperatorNumeric
    {
      get { return _simOperatorNumeric; }
      set { _simOperatorNumeric = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetImageRequest")]
  public partial class GetImageRequest : global::ProtoBuf.IExtensible
  {
    public GetImageRequest() {}
    

    private string _appId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AppId
    {
      get { return _appId; }
      set { _appId = value; }
    }

    private GetImageRequest.AppImageUsage _imageUsage = GetImageRequest.AppImageUsage.Icon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"imageUsage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(GetImageRequest.AppImageUsage.Icon)]
    public GetImageRequest.AppImageUsage ImageUsage
    {
      get { return _imageUsage; }
      set { _imageUsage = value; }
    }

    private string _imageId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"imageId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ImageId
    {
      get { return _imageId; }
      set { _imageId = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AppImageUsage")]
    public enum AppImageUsage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ICON", Value=0)]
      Icon = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCREENSHOT", Value=1)]
      Screenshot = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCREENSHOT_THUMBNAIL", Value=2)]
      ScreenshotThumbnail = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROMO_BADGE", Value=3)]
      PromoBadge = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BILING_ICON", Value=4)]
      BilingIcon = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetImageResponse")]
  public partial class GetImageResponse : global::ProtoBuf.IExtensible
  {
    public GetImageResponse() {}
    

    private byte[] _imageData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"imageData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] ImageData
    {
      get { return _imageData; }
      set { _imageData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    

    private RequestContext _context = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public RequestContext Context
    {
      get { return _context; }
      set { _context = value; }
    }
    private readonly global::System.Collections.Generic.List<Request.RequestGroup> _requestgroup = new global::System.Collections.Generic.List<Request.RequestGroup>();
    [global::ProtoBuf.ProtoMember(2, Name=@"requestgroup", DataFormat = global::ProtoBuf.DataFormat.Group)]
    public global::System.Collections.Generic.List<Request.RequestGroup> Requestgroup
    {
      get { return _requestgroup; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestGroup")]
  public partial class RequestGroup : global::ProtoBuf.IExtensible
  {
    public RequestGroup() {}
    

    private AppsRequest _appsRequest = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"appsRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AppsRequest AppsRequest
    {
      get { return _appsRequest; }
      set { _appsRequest = value; }
    }

    private CommentsRequest _commentsRequest = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"commentsRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CommentsRequest CommentsRequest
    {
      get { return _commentsRequest; }
      set { _commentsRequest = value; }
    }

    private GetImageRequest _imageRequest = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"imageRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GetImageRequest ImageRequest
    {
      get { return _imageRequest; }
      set { _imageRequest = value; }
    }

    private SubCategoriesRequest _subCategoriesRequest = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"subCategoriesRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SubCategoriesRequest SubCategoriesRequest
    {
      get { return _subCategoriesRequest; }
      set { _subCategoriesRequest = value; }
    }

    private CategoriesRequest _categoriesRequest = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"categoriesRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CategoriesRequest CategoriesRequest
    {
      get { return _categoriesRequest; }
      set { _categoriesRequest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseContext")]
  public partial class ResponseContext : global::ProtoBuf.IExtensible
  {
    public ResponseContext() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _unknown1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"unknown1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Unknown1
    {
      get { return _unknown1; }
      set { _unknown1 = value; }
    }

    private string _unknown2 = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unknown2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Unknown2
    {
      get { return _unknown2; }
      set { _unknown2 = value; }
    }

    private int _unknown3 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"unknown3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Unknown3
    {
      get { return _unknown3; }
      set { _unknown3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private readonly global::System.Collections.Generic.List<Response.ResponseGroup> _responsegroup = new global::System.Collections.Generic.List<Response.ResponseGroup>();
    [global::ProtoBuf.ProtoMember(1, Name=@"responsegroup", DataFormat = global::ProtoBuf.DataFormat.Group)]
    public global::System.Collections.Generic.List<Response.ResponseGroup> Responsegroup
    {
      get { return _responsegroup; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseGroup")]
  public partial class ResponseGroup : global::ProtoBuf.IExtensible
  {
    public ResponseGroup() {}
    

    private ResponseContext _context = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ResponseContext Context
    {
      get { return _context; }
      set { _context = value; }
    }

    private AppsResponse _appsResponse = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"appsResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AppsResponse AppsResponse
    {
      get { return _appsResponse; }
      set { _appsResponse = value; }
    }

    private CommentsResponse _commentsResponse = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"commentsResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CommentsResponse CommentsResponse
    {
      get { return _commentsResponse; }
      set { _commentsResponse = value; }
    }

    private GetImageResponse _imageResponse = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"imageResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GetImageResponse ImageResponse
    {
      get { return _imageResponse; }
      set { _imageResponse = value; }
    }

    private CategoriesResponse _categoriesResponse = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"categoriesResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CategoriesResponse CategoriesResponse
    {
      get { return _categoriesResponse; }
      set { _categoriesResponse = value; }
    }

    private SubCategoriesResponse _subCategoriesResponse = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"subCategoriesResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SubCategoriesResponse SubCategoriesResponse
    {
      get { return _subCategoriesResponse; }
      set { _subCategoriesResponse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AppType")]
    public enum AppType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPLICATION", Value=1)]
      Application = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RINGTONE", Value=2)]
      Ringtone = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALLPAPER", Value=3)]
      Wallpaper = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME", Value=4)]
      Game = 4
    }
  
}